name: OWASP ZAP Scan

on:
  workflow_dispatch:  # allows manual run from Actions tab
  push:                # optional â€“ runs when you push code
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw --network="host" ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t https://demo.testfire.net \
            -r zap_report.html
        continue-on-error: true  # even if some alerts exist, continue to next step

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
