name: OWASP ZAP Baseline Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --user root \
            -v ${{ github.workspace }}:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t https://demo.testfire.net \
            -r /zap/wrk/zap_report.html
        continue-on-error: true

      - name: Verify report exists
        run: ls -al ${{ github.workspace }}

      - name: Upload ZAP Report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
